version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6.0
  pre-build:
    commands:
      - dotnet restore AWSCodePipelineDemo/AWSCodePipelineDemo.csproj
      # - dotnet publish -c Release -o ./publish
  build:
    commands:
      - dotnet build AWSCodePipelineDemo/AWSCodePipelineDemo.csproj
  post_build:
    commands:
      - dotnet publish -c Release -o ./app/ AWSCodePipelineDemo/AWSCodePipelineDemo.csproj
artifacts:
  files: 
    - '**/*'
  # base-directory: ./publish
